name: Docker Image CI
on: [push]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: docker pull k8s.gcr.io/ingress-nginx/controller:v0.46.0@sha256:52f0058bed0a17ab0fb35628ba97e8d52b5d32299fbc03cc0f6c7b9ff036b61a 
    - run: docker tag k8s.gcr.io/ingress-nginx/controller:v0.46.0@sha256:52f0058bed0a17ab0fb35628ba97e8d52b5d32299fbc03cc0f6c7b9ff036b61a 20201231/ingress-nginx-controller:v0.46.0
    - run: docker push 20201231/ingress-nginx-controller:v0.46.0
