name: Docker Image CI

on:
  push:
    branches: [ https://github.com/Queetinliu/make-gcr-io ]
  pull_request:
    branches: [ https://github.com/Queetinliu/make-gcr-io ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfile-ingress-controller --tag controller:v0.46.0@sha256:52f0058bed0a17ab0fb35628ba97e8d52b5d32299fbc03cc0f6c7b9ff036b61a
